#############
### INPUT ###
#############

input {
    kb_layout = us,br
    kb_variant =,abnt2
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = false

    sensitivity = 0.2
    accel_profile = adaptive

    follow_mouse = 1

    touchpad {
        tap-to-click = true
        natural_scroll = false
    }

    # tablet {
    #
    #     left_handed = true
    #     transform = 2
    #
    # }
    tablet {
        left_handed = true
        transform = 2
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

binds {
    workspace_center_on = 1 #Put the mouse on the last focused window when switching workspaces
    movefocus_cycles_fullscreen = true #When moving focus, cycle through fullscreen windows as well
}

cursor {
    sync_gsettings_theme = true # Syncs cursor theme with gsettings (GNOME/KDE/etc)
    inactive_timeout = 3 # Time in seconds to switch to inactive cursor after no movement
    hide_on_key_press = true # Hides cursor when typing
    warp_on_change_workspace = true # Warps cursor to center of screen when changing workspaces
    persistent_warps = true # Remembers cursor position on each monitor when switching
}

