plugin {
    hyprscrolling {
        column_width = 0.7
        fullscreen_on_one_column = true
    }
}

plugin:hyprglass {
    default_theme = dark
    default_preset = glass
    tint_color = 0x8899aa22

    brightness = 0.0
    dark:brightness = 0.2
    light:adaptive_boost = 0.5

    preset = name:clear, glass_opacity:0.8, blur_strength:1.5
    preset = name:clear:dark, brightness:0.7
    preset = name:clear:light, brightness:1.2

    preset = name:contrasted, inherits:high_contrast, contrast:1.2, adaptive_dim:1.5
    preset = name:contrasted:dark, tint_color:0x02142aa9

    layers:enabled = 1
    layers:namespaces = waybar, swaync, quickshell:bezel
    layers:exclude_namespaces = debug-panel
    layers:preset = subtle
    layers:namespace_presets = quickshell:bezel:ui
    layers:namespace_mask_thresholds = waybar=0.05, quickshell:bezel=0.3
}
