$HOME/.config/waybar/theme.css|$HOME/.local/share/scripts/startwaybar.sh
@define-color bar-bg rgba(0, 0, 0, 0.1);

@define-color main-bg #070B14;
@define-color main-fg #D8E2F0;

@define-color active-bg #00C6E2;
@define-color active-fg #070B14;

@define-color hover-bg #FB5388;
@define-color hover-fg #070B14;

@define-color red #E9395F;
@define-color orange #FF7A5C;
@define-color yellow #EE94AC;
@define-color green #2EC2BC;
@define-color blue #00C6E2;
@define-color purple #8B7EBF;
@define-color pink #FB5388;
@define-color aqua #118998;