[General]
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""
Font="Electroharmonix"
FontSize="12"
KeyboardSize="0.4"
RoundCorners="20"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"
HeaderText=""

BackgroundPlaceholder=""
Background="Backgrounds/japanese_aesthetic.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#32302f"
DateTextColor="#32302f"
TimeTextColor="#32302f"

FormBackgroundColor="#21222C"
BackgroundColor="#21222C"
DimBackgroundColor="#21222C"

LoginFieldBackgroundColor="#222222"
PasswordFieldBackgroundColor="#222222"
LoginFieldTextColor="#32302f"
PasswordFieldTextColor="#32302f"
UserIconColor="#32302f"
PasswordIconColor="#32302f"

PlaceholderTextColor="#7c6f64"
WarningColor="#32302f"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#32302f"
SystemButtonsIconsColor="#32302f"
SessionButtonTextColor="#32302f"
VirtualKeyboardButtonTextColor="#32302f"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="#7c6f64"
DropdownBackgroundColor="#32302f"

HighlightTextColor="#7c6f64"
HighlightBackgroundColor="#32302f"
HighlightBorderColor="transparent"

HoverUserIconColor="#7c6f64"
HoverPasswordIconColor="#7c6f64"
HoverSystemButtonsIconsColor="#7c6f64"
HoverSessionButtonTextColor="#7c6f64"
HoverVirtualKeyboardButtonTextColor="#7c6f64"

PartialBlur=""
FullBlur=""
BlurMax=""
Blur=""
HaveFormBackground="false"
FormPosition="left"

VirtualKeyboardPosition="left"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
