$GTK_THEME =Kanagawa-Wave
$ICON_THEME =Tela-circle-dracula
$CURSOR_THEME =Kanagawa-cursors
$CURSOR_SIZE =20
$COLOR_SCHEME =prefer-dark

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME
exec = gsettings set org.gnome.desktop.interface cursor-theme $CURSOR_THEME
exec = gsettings set org.gnome.desktop.interface cursor-size $CURSOR_SIZE
exec = hyprctl setcursor $CURSOR_THEME $CURSOR_SIZE

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(7e9cd8ff) rgba(957fb8ff) 45deg
    col.inactive_border = rgba(54546dcc) rgba(363646cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(7e9cd8ff) rgba(957fb8ff) 45deg
    col.border_inactive = rgba(54546dcc) rgba(363646cc) 45deg
    col.border_locked_active = rgba(7e9cd8ff) rgba(957fb8ff) 45deg
    col.border_locked_inactive = rgba(54546dcc) rgba(363646cc) 45deg
}

decoration {
    rounding = 10
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar