$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty

## name:     Kanagawa Wave
## author:   Based on rebelot/kanagawa.nvim
## blurb:    Dark theme inspired by the great wave off Kanagawa

foreground              #DCD7BA
background              #1F1F28
selection_foreground    #16161D
selection_background    #2D4F67

cursor                  #C8C093
cursor_text_color       #1F1F28

url_color               #7E9CD8

active_border_color     #7E9CD8
inactive_border_color   #54546D
bell_border_color       #E6C384

active_tab_foreground   #16161D
active_tab_background   #7E9CD8
inactive_tab_foreground #DCD7BA
inactive_tab_background #16161D
tab_bar_background      #16161D

mark1_foreground #1F1F28
mark1_background #7E9CD8
mark2_foreground #1F1F28
mark2_background #957FB8
mark3_foreground #1F1F28
mark3_background #6A9589

# black
color0 #363646
color8 #54546D

# red
color1  #C34043
color9  #E82424

# green
color2  #76946A
color10 #98BB6C

# yellow
color3  #C0A36E
color11 #E6C384

# blue
color4  #7E9CD8
color12 #7FB4CA

# magenta
color5  #957FB8
color13 #938AA9

# cyan
color6  #6A9589
color14 #7AA89F

# white
color7  #DCD7BA
color15 #C8C093