$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty

## name:     Everforest Dark Hard
## author:   Sainnhe
## license:  MIT

# The basic colors
foreground              #d3c6aa
background              #272e33
selection_foreground    #9da9a0
selection_background    #503946

# Cursor colors
cursor                  #d3c6aa
cursor_text_color       #272e33

# URL underline color when hovering with mouse
url_color               #7fbbb3

# Kitty window border colors
active_border_color     #a7c080
inactive_border_color   #859289
bell_border_color       #e67e80

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #272e33
active_tab_background   #a7c080
inactive_tab_foreground #d3c6aa
inactive_tab_background #2e383c
tab_bar_background      #1e2326

# Colors for marks
mark1_foreground #272e33
mark1_background #7fbbb3
mark2_foreground #272e33
mark2_background #d699b6
mark3_foreground #272e33
mark3_background #dbbc7f

# The 16 terminal colors

# black
color0 #4b565c
color8 #5c6a72

# red
color1 #e67e80
color9 #f85552

# green
color2  #a7c080
color10 #a7c080

# yellow
color3  #dbbc7f
color11 #dfa000

# blue
color4  #7fbbb3
color12 #3a94c5

# magenta
color5  #d699b6
color13 #df69ba

# cyan
color6  #83c092
color14 #35a77c

# white
color7  #d3c6aa
color15 #dfddc8
