$GTK_THEME=E-Ink-Dark
$ICON_THEME=Papirus-Dark
$COLOR_SCHEME=prefer-dark

# Optional: The varibles above will be set automatically when the theme is loaded
# This exec commands will soon be deprecated

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    # Borda Ativa: O Branco E-Ink (#CCCCCC)
    col.active_border = rgba(CCCCCCff) rgba(B3B3B3ff) 45deg
    # Borda Inativa: Cinza Escuro sutil (#333333)
    col.inactive_border = rgba(333333cc) rgba(222222cc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(CCCCCCff) rgba(B3B3B3ff) 45deg
    col.border_inactive = rgba(333333cc) rgba(222222cc) 45deg
    col.border_locked_active = rgba(CCCCCCff) rgba(B3B3B3ff) 45deg
    col.border_locked_inactive = rgba(333333cc) rgba(222222cc) 45deg
}

decoration {
    rounding = 8
    shadow:enabled = true
    shadow:range = 20
    shadow:render_power = 3
    shadow:color = rgba(00000066)

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
