$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty

## name:     E-Ink Dark (Monochrome)
## author:   Kindle Dark Mode Inspired
## license:  MIT

# The basic colors
foreground              #CCCCCC
background              #121212
selection_foreground    #121212
selection_background    #CCCCCC

# Cursor colors
cursor                  #CCCCCC
cursor_text_color       #121212

# URL underline color
url_color               #FFFFFF

# Kitty window border colors
active_border_color     #CCCCCC
inactive_border_color   #333333
bell_border_color       #808080

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #121212
active_tab_background   #CCCCCC
inactive_tab_foreground #CCCCCC
inactive_tab_background #222222
tab_bar_background      #121212

# Colors for marks (Alto contraste invertido)
mark1_foreground #121212
mark1_background #CCCCCC
mark2_foreground #121212
mark2_background #B3B3B3
mark3_foreground #121212
mark3_background #999999

# The 16 terminal colors (Monochrome Dark Map)

# black (Fundo)
color0 #121212
color8 #333333

# red (Dark Grey)
color1 #666666
color9 #4D4D4D

# green (Mid Grey)
color2  #808080
color10 #666666

# yellow (Light Grey)
color3  #B3B3B3
color11 #999999

# blue (Focus Grey)
color4  #CCCCCC
color12 #B3B3B3

# magenta (Mid Grey)
color5  #999999
color13 #808080

# cyan (Light Grey)
color6  #B3B3B3
color14 #999999

# white (Texto Principal)
color7  #CCCCCC
color15 #FFFFFF
