$HOME/.config/rofi/theme.rasi
* {
    /* Fundo Preto Tinta */
    background:           #121212E3;
    background-alt:       #1A1A1AFF;
    
    /* Texto Branco E-Ink (#CCCCCC) */
    foreground:           #CCCCCCFF;
    
    /* Seleção: Fundo Branco, Texto Preto (Invertido) */
    selected-background:  #CCCCCCFF;
    selected-foreground:  #121212FF;
    
    border:               #CCCCCCFF;
    active:               #FFFFFF;
    urgent:               #808080FF;
}
