$HOME/.config/waybar/theme.css|/home/mateusdall/.local/share/scripts/startwaybar.sh
@define-color bar-bg rgba(18, 18, 18, 0.95);

@define-color main-bg #121212;
@define-color main-fg #CCCCCC;

@define-color active-bg #CCCCCC;
@define-color active-fg #121212;

@define-color hover-bg #333333;
@define-color hover-fg #FFFFFF;

/* Cores mapeadas para monocromático escuro */
@define-color red #666666;
@define-color orange #808080;
@define-color yellow #B3B3B3;
@define-color green #808080;
@define-color blue #CCCCCC;
@define-color purple #999999;
@define-color pink #808080;
@define-color aqua #B3B3B3;
