
## name:     NeonVibes
## blurb:    Dark cyan & pink neon theme

foreground              #D8E2F0
background              #0D1321
selection_foreground    #070B14
selection_background    #15405C

cursor                  #5BB7C0
cursor_text_color       #070B14

url_color               #5BB7C0

active_border_color     #5BB7C0
inactive_border_color   #3A4160
bell_border_color       #EE94AC

active_tab_foreground   #070B14
active_tab_background   #5BB7C0
inactive_tab_foreground #D8E2F0
inactive_tab_background #070B14
tab_bar_background      #070B14

mark1_foreground #0D1321
mark1_background #5BB7C0
mark2_foreground #0D1321
mark2_background #FB5388
mark3_foreground #0D1321
mark3_background #2EC2BC

# black
color0 #1A1F35
color8 #3A4160

# red
color1  #E9395F
color9  #E9395F

# green
color2  #2EC2BC
color10 #2EC2BC

# yellow
color3  #EE94AC
color11 #EE94AC

# blue
color4  #5BB7C0
color12 #5BB7C0

# magenta
color5  #FB5388
color13 #FB5388

# cyan
color6  #118998
color14 #118998

# white
color7  #D8E2F0
color15 #A8B7CC