$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty

## name:     LavenderDusk
## blurb:    Soft blue hour, lavender & sunset

foreground              #E8D9E8
background              #1E1E2D
selection_foreground    #1E1E2D
selection_background    #D3A5D2

cursor                  #E1A6CE
cursor_text_color       #1E1E2D

url_color               #8E91D2

active_border_color     #AAA0D8
inactive_border_color   #414260
bell_border_color       #E1A6CE

active_tab_foreground   #1E1E2D
active_tab_background   #AAA0D8
inactive_tab_foreground #B7B4E2
inactive_tab_background #29283E
tab_bar_background      #1E1E2D

mark1_foreground #1E1E2D
mark1_background #D3A5D2
mark2_foreground #1E1E2D
mark2_background #8E91D2
mark3_foreground #1E1E2D
mark3_background #E1A6CE


# black
color0  #1E1E2D
color8  #5A6090

# red
color1  #C77D9F
color9  #E1A6CE

# green
color2  #7290D4
color10 #8AA0DD

# yellow
color3  #D3A5D2
color11 #EBA8D0

# blue
color4  #737FC5
color12 #8E91D2

# magenta
color5  #C0A4D6
color13 #E1A6CE

# cyan
color6  #8AA0DD
color14 #B7B4E2

# white
color7  #E8D9E8
color15 #F1EAF1
