$HOME/.config/waybar/theme.css|$HOME/.local/share/scripts/startwaybar.sh
@define-color bar-bg rgba(30, 30, 45, 0.75);

@define-color main-bg #1E1E2D;
@define-color main-fg #E8D9E8;

@define-color active-bg #AAA0D8;
@define-color active-fg #1E1E2D;

@define-color hover-bg #AC93EE;
@define-color hover-fg #1E1E2D;

@define-color red #C77D9F;
@define-color orange #EBA8D0;
@define-color yellow #D3A5D2;
@define-color green #7290D4;
@define-color blue #737FC5;
@define-color purple #C0A4D6;
@define-color pink #E1A6CE;
@define-color aqua #8E91D2;
