$HOME/.config/waybar/theme.css|$HOME/.local/share/scripts/startwaybar.sh
@define-color bar-bg rgba(5,1,12,0);
@define-color main-bg rgba(5,1,12,0.8);
@define-color main-fg rgba(195,170,240,0.8);
@define-color active-bg rgba(129,77,222,0.4);
@define-color active-fg rgba(222,204,255,1);
@define-color hover-bg rgba(92,75,125,0.4);
@define-color hover-fg rgba(194,170,240,0.8);

@define-color red    #8e4b5d;
@define-color orange #a67c5e;
@define-color yellow #b3a06a;
@define-color green  #6c8a7e;
@define-color blue   #6678a6;
@define-color purple #81549d;
@define-color pink   #c3aaf0;
@define-color aqua   #78a6a2;
